name: code-review

on: [push, pull_request]

jobs:
  code-review:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '>=16'
          cache: 'npm'

      - name: Install dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Install dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint (Backend)
        working-directory: ./backend
        run: npx eslint .

      - name: Run ESLint (Frontend)
        working-directory: ./frontend
        run: npx eslint .

      - name: Run JSHint (Backend)
        working-directory: ./backend
        run: npx jshint .

      - name: Run JSHint (Frontend)
        working-directory: ./frontend
        run: npx jshint .

      - name: Run Snyk (Backend)
        working-directory: ./backend
        run: npx snyk test

      - name: Run Snyk (Frontend)
        working-directory: ./frontend
        run: npx snyk test
